import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#212121]">
      <head>
        <meta charSet="UTF-8" />
        <title>NextJs Clone coding</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
